<font size="6">Name : Digesh Patel</font><br>
<font size="6">ID : 202318038</font><br>
<font size="6">Msc Data Science Sem 2</font><br>
<font size="6">Big Data Processing</font><br>

**<font size="7">Assignment 1 :Task - A</font><br>**

**<font size="5">Develop Python code to perform block multiplication on two given matrices of size 2n x 2n </font><br>**

<font size="5">1) with numpy</font>

In [17]:
import numpy as np

In [39]:
def block_multiplication(matrix1, matrix2, middle):

    # Split matrices into 4 blocks
    a11 = matrix1[:middle, :middle]
    a12 = matrix1[:middle, middle:]
    a21 = matrix1[middle:, :middle]
    a22 = matrix1[middle:, middle:]

    b11 = matrix2[:middle, :middle]
    b12 = matrix2[:middle, middle:]
    b21 = matrix2[middle:, :middle]
    b22 = matrix2[middle:, middle:]

    #  block multiplication
    c11 = np.dot(a11, b11) + np.dot(a12, b21)
    c12 = np.dot(a11, b12) + np.dot(a12, b22)
    c21 = np.dot(a21, b11) + np.dot(a22, b21)
    c22 = np.dot(a21, b12) + np.dot(a22, b22)

    # Concatenate block results
    result = np.hstack((np.vstack((c11, c21)), np.vstack((c12, c22))))

    return result


matrix1 = [[1, 2, 3, 4],
          [5, 6, 7, 8],
          [9, 10, 11, 12],
          [13, 14, 15, 16]]

matrix2 = [[17, 18, 19, 20],
          [21, 22, 23, 24],
          [25, 26, 27, 28],
          [29, 30, 31, 32]]

na = np.array(matrix1)
nb = np.array(matrix2)
middle = int(len(na)/2)


result = block_multiplication(na,nb,middle)

print("Matrix A:")
print(na)
print("\nMatrix B:")
print(nb)
print("\nResult :")
print(result)


Matrix A:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]

Matrix B:
[[17 18 19 20]
 [21 22 23 24]
 [25 26 27 28]
 [29 30 31 32]]

Result :
[[ 250  260  270  280]
 [ 618  644  670  696]
 [ 986 1028 1070 1112]
 [1354 1412 1470 1528]]


<font size="5">2) without numpy</font>

In [40]:
def block_multiplication(matrix1, matrix2, block_size):
    size = len(matrix1)
    result = [[0 for _ in range(size)] for _ in range(size)]

    for i in range(0, size, block_size):
        for j in range(0, size, block_size):
            for k in range(0, size, block_size):
                for ii in range(i, min(i + block_size, size)):
                    for jj in range(j, min(j + block_size, size)):
                        for kk in range(k, min(k + block_size, size)):
                            result[ii][jj] += matrix1[ii][kk] * matrix2[kk][jj]

    return result

matrix1 = [[1, 2, 3, 4],
          [5, 6, 7, 8],
          [9, 10, 11, 12],
          [13, 14, 15, 16]]

matrix2 = [[17, 18, 19, 20],
          [21, 22, 23, 24],
          [25, 26, 27, 28],
          [29, 30, 31, 32]]

block_size = 2
result = block_multiplication(matrix1, matrix2, block_size)

print("Matrix A:")
for row in matrix1:
  print(row)

print("\nMatrix B:")
for row in matrix2:
  print(row)

print("\nResult :")
for row in result:
  print(row)


Matrix A:
[1, 2, 3, 4]
[5, 6, 7, 8]
[9, 10, 11, 12]
[13, 14, 15, 16]

Matrix B:
[17, 18, 19, 20]
[21, 22, 23, 24]
[25, 26, 27, 28]
[29, 30, 31, 32]

Result :
[250, 260, 270, 280]
[618, 644, 670, 696]
[986, 1028, 1070, 1112]
[1354, 1412, 1470, 1528]
